# This is a config for E2B sandbox template.
# You can use template ID (t5f4fce2pypl6qkwf33q) or template name (v0-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-clone')

team_id = "40ac5d05-33d5-4745-9195-bc14389edb31"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-clone"
template_id = "t5f4fce2pypl6qkwf33q"
